customhost = "employee.cqk1qu4znbca.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chuaphingswen-employee"
customregion = "us-east-1"
